echo_green "Installing Atom packages..."

apm install Sublime-Style-Column-Selection
apm install advanced-open-file
apm install atom-beautify
apm install atom-bootstrap4
apm install atom-html-preview
apm install atom-jest-snippets
apm install atom-ternjs
apm install autocomplete-modules
apm install autocomplete-python
apm install busy-signal
apm install color-picker
apm install emmet
apm install file-icons
apm install highlight-selected
apm install intentions
apm install jquery-snippets
apm install language-vue
apm install language-x86-64-assembly
apm install linter
apm install linter-clang
apm install linter-eslint
apm install linter-ui-default
apm install minimap
apm install pigments
apm install platformio-ide-terminal
apm install react
apm install script
apm install todo-show
apm install vue-format
